name: Build and Deploy Bicep Template and Docker Image

env:
  REGISTRY_NAME: 'DuxAppacr'
  IMAGE_VERSION: ''

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  # Job to build the Bicep template
  build-bicep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/cli@v1.0.7
        with:
          inlineScript: |
            az version

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Bicep Template
        run: |
          # Validate the Bicep template
          az bicep build --file main.bicep

  # Job to deploy the Bicep template
  deploy-bicep:
    runs-on: ubuntu-latest
    needs: build-bicep  # Ensure this job runs after the Bicep build job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep Template
        run: |
          az deployment group create \
            --resource-group BCSAI2024-DEVOPS-STUDENTS-A-DEV \
            --template-file main.bicep \
            --parameters main.parameters.json

  # Job to build and push Docker image
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Login to Azure
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: |
          az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID

      - name: Check Azure CLI Version
        run: |
          az --version

      - name: Get ACR Credentials
        id: acr-credentials
        run: |
          ACR_USERNAME=$(az acr credential show --name DuxAppacr --query "username" -o tsv)
          ACR_PASSWORD=$(az acr credential show --name DuxAppacr --query "passwords[0].value" -o tsv)
          echo "ACR_USERNAME=${ACR_USERNAME}" >> $GITHUB_ENV
          echo "ACR_PASSWORD=${ACR_PASSWORD}" >> $GITHUB_ENV

      - name: Login to Azure Container Registry
        run: |
          echo "${{ env.ACR_PASSWORD }}" | docker login DuxAppacr.azurecr.io -u "${{ env.ACR_USERNAME }}" --password-stdin

      - name: Set Image Version
        id: image-version
        run: |
          echo "IMAGE_VERSION=$(date +'%Y.%m.%d.%H.%M')" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build . -t DuxAppacr.azurecr.io/my-app:latest

      - name: Push Docker Image
        run: |
          docker push DuxAppacr.azurecr.io/my-app:latest

  # Job to deploy Docker image to Azure Web App
  deploy-docker:
    runs-on: ubuntu-latest
    needs: build-docker  # Ensure this job runs after the Docker build job

    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Docker Image to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "duxapp-app"
          images: "${{ env.REGISTRY_NAME }}.azurecr.io/my-app:${{ env.IMAGE_VERSION }}"

      - name: Check Azure CLI Version
        run: |
          az --version
